
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 21 21:27:33 CST 2022
//----------------------------------------------------

package compiler.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Class = 14;
  public static final int True = 11;
  public static final int STRING_LITERAL = 50;
  public static final int Coma = 45;
  public static final int Digit = 17;
  public static final int If = 5;
  public static final int Id = 16;
  public static final int Void = 13;
  public static final int Hex_literal = 21;
  public static final int NOT_EQUAL = 30;
  public static final int GREATER = 22;
  public static final int Menos = 37;
  public static final int Mas = 36;
  public static final int Else = 7;
  public static final int Hex_digit = 19;
  public static final int LESS = 23;
  public static final int Break = 9;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int Return = 8;
  public static final int PLUS_EQUAL = 26;
  public static final int Llave_C = 42;
  public static final int MINUS_EQUAL = 28;
  public static final int LESS_EQUAL = 24;
  public static final int Llave_A = 41;
  public static final int Division = 39;
  public static final int Int = 2;
  public static final int ASSIGN = 27;
  public static final int For = 6;
  public static final int EOF = 0;
  public static final int EQUAL = 29;
  public static final int GREATER_EQUAL = 25;
  public static final int error = 1;
  public static final int ComillasDoble = 48;
  public static final int Corche_C = 44;
  public static final int Corche_A = 43;
  public static final int False = 12;
  public static final int Decimal_literal = 20;
  public static final int Alpha = 18;
  public static final int ERROR = 49;
  public static final int RIGHT_PAR = 34;
  public static final int Continue = 10;
  public static final int Exclamacion = 46;
  public static final int Callout = 4;
  public static final int Mod = 40;
  public static final int Punto_coma = 35;
  public static final int Multiplicacion = 38;
  public static final int Boolean = 3;
  public static final int LEFT_PAR = 33;
  public static final int Program = 15;
  public static final int Comillas = 47;
}

