
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 25 22:06:12 CST 2022
//----------------------------------------------------

package compiler.irt;

import java_cup.runtime.Symbol;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Nov 25 22:06:12 CST 2022
  */
public class IRT extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public IRT() {super();}

  /** Constructor which sets the default scanner. */
  public IRT(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public IRT(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\133\000\002\002\004\000\002\002\003\000\002\003" +
    "\010\000\002\031\003\000\002\031\006\000\002\004\007" +
    "\000\002\004\002\000\002\037\005\000\002\037\002\000" +
    "\002\044\002\000\002\005\012\000\002\045\002\000\002" +
    "\005\012\000\002\005\002\000\002\046\002\000\002\032" +
    "\006\000\002\032\002\000\002\047\002\000\002\033\007" +
    "\000\002\033\002\000\002\006\006\000\002\007\007\000" +
    "\002\007\002\000\002\034\005\000\002\034\002\000\002" +
    "\010\003\000\002\010\003\000\002\050\002\000\002\011" +
    "\010\000\002\011\005\000\002\011\011\000\002\011\012" +
    "\000\002\011\006\000\002\011\005\000\002\011\005\000" +
    "\002\011\004\000\002\011\002\000\002\035\004\000\002" +
    "\035\002\000\002\036\003\000\002\036\002\000\002\012" +
    "\003\000\002\012\003\000\002\012\003\000\002\013\006" +
    "\000\002\013\007\000\002\040\004\000\002\040\002\000" +
    "\002\041\005\000\002\041\002\000\002\042\005\000\002" +
    "\042\002\000\002\043\005\000\002\043\002\000\002\014" +
    "\003\000\002\015\003\000\002\015\006\000\002\016\003" +
    "\000\002\016\003\000\002\016\003\000\002\016\005\000" +
    "\002\016\004\000\002\016\004\000\002\016\005\000\002" +
    "\017\003\000\002\017\003\000\002\020\003\000\002\020" +
    "\003\000\002\020\003\000\002\020\003\000\002\021\003" +
    "\000\002\021\003\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\022\003\000\002\022\003\000\002" +
    "\022\003\000\002\022\003\000\002\023\003\000\002\023" +
    "\003\000\002\024\003\000\002\024\003\000\002\025\003" +
    "\000\002\025\003\000\002\025\003\000\002\026\003\000" +
    "\002\026\003\000\002\026\003\000\002\027\003\000\002" +
    "\027\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\004\020\005\001\002\000\004\002\000\001" +
    "\002\000\004\021\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\004\053\011\001\002\000" +
    "\012\004\ufffb\005\ufffb\017\ufffb\054\ufffb\001\002\000\012" +
    "\004\016\005\017\017\013\054\ufff4\001\002\000\004\022" +
    "\242\001\002\000\004\054\241\001\002\000\004\022\020" +
    "\001\002\000\004\022\uffe8\001\002\000\004\022\uffe7\001" +
    "\002\000\012\043\036\045\ufffe\055\030\057\ufffe\001\002" +
    "\000\006\045\ufff9\057\022\001\002\000\004\022\025\001" +
    "\002\000\004\045\024\001\002\000\012\004\ufffc\005\ufffc" +
    "\017\ufffc\054\ufffc\001\002\000\010\045\ufffe\055\030\057" +
    "\ufffe\001\002\000\006\045\ufff9\057\022\001\002\000\004" +
    "\045\ufffa\001\002\000\010\023\031\026\032\027\034\001" +
    "\002\000\046\030\uffa9\031\uffa9\032\uffa9\033\uffa9\037\uffa9" +
    "\040\uffa9\041\uffa9\042\uffa9\044\uffa9\045\uffa9\046\uffa9\047" +
    "\uffa9\050\uffa9\051\uffa9\052\uffa9\053\uffa9\056\uffa9\057\uffa9" +
    "\001\002\000\046\030\uffab\031\uffab\032\uffab\033\uffab\037" +
    "\uffab\040\uffab\041\uffab\042\uffab\044\uffab\045\uffab\046\uffab" +
    "\047\uffab\050\uffab\051\uffab\052\uffab\053\uffab\056\uffab\057" +
    "\uffab\001\002\000\004\056\035\001\002\000\046\030\uffaa" +
    "\031\uffaa\032\uffaa\033\uffaa\037\uffaa\040\uffaa\041\uffaa\042" +
    "\uffaa\044\uffaa\045\uffaa\046\uffaa\047\uffaa\050\uffaa\051\uffaa" +
    "\052\uffaa\053\uffaa\056\uffaa\057\uffaa\001\002\000\006\045" +
    "\ufffd\057\ufffd\001\002\000\010\004\016\005\017\044\ufff1" +
    "\001\002\000\004\022\231\001\002\000\004\044\041\001" +
    "\002\000\004\053\ufff8\001\002\000\004\053\043\001\002" +
    "\000\030\004\016\005\017\006\uffeb\007\uffeb\010\uffeb\012" +
    "\uffeb\013\uffeb\014\uffeb\022\uffeb\053\uffeb\054\uffeb\001\002" +
    "\000\012\004\016\005\017\017\013\054\ufff4\001\002\000" +
    "\004\054\ufff7\001\002\000\004\022\047\001\002\000\004" +
    "\043\036\001\002\000\004\022\222\001\002\000\024\006" +
    "\052\007\057\010\063\012\055\013\054\014\060\022\061" +
    "\053\043\054\uffdd\001\002\000\004\043\206\001\002\000" +
    "\004\045\204\001\002\000\004\045\202\001\002\000\032" +
    "\006\052\015\075\016\076\022\061\023\031\026\032\027" +
    "\034\043\100\045\uffd9\047\104\060\077\062\101\001\002" +
    "\000\004\043\166\001\002\000\004\043\156\001\002\000" +
    "\004\045\154\001\002\000\060\030\uffca\031\uffca\032\uffca" +
    "\033\uffca\034\uffca\035\uffca\036\uffca\037\uffca\040\uffca\041" +
    "\uffca\042\uffca\043\uffcb\044\uffca\045\uffca\046\uffca\047\uffca" +
    "\050\uffca\051\uffca\052\uffca\053\uffca\055\151\056\uffca\057" +
    "\uffca\001\002\000\024\006\052\007\057\010\063\012\055" +
    "\013\054\014\060\022\061\053\043\054\uffdd\001\002\000" +
    "\004\022\141\001\002\000\004\054\140\001\002\000\010" +
    "\034\067\035\071\036\066\001\002\000\030\006\uffd6\015" +
    "\uffd6\016\uffd6\022\uffd6\023\uffd6\026\uffd6\027\uffd6\043\uffd6" +
    "\047\uffd6\060\uffd6\062\uffd6\001\002\000\030\006\uffd7\015" +
    "\uffd7\016\uffd7\022\uffd7\023\uffd7\026\uffd7\027\uffd7\043\uffd7" +
    "\047\uffd7\060\uffd7\062\uffd7\001\002\000\030\006\052\015" +
    "\075\016\076\022\061\023\031\026\032\027\034\043\100" +
    "\047\104\060\077\062\101\001\002\000\030\006\uffd8\015" +
    "\uffd8\016\uffd8\022\uffd8\023\uffd8\026\uffd8\027\uffd8\043\uffd8" +
    "\047\uffd8\060\uffd8\062\uffd8\001\002\000\046\030\uffc7\031" +
    "\uffc7\032\uffc7\033\uffc7\037\uffc7\040\uffc7\041\uffc7\042\uffc7" +
    "\044\uffc7\045\uffc7\046\uffc7\047\uffc7\050\uffc7\051\uffc7\052" +
    "\uffc7\053\uffc7\056\uffc7\057\uffc7\001\002\000\046\030\uffc8" +
    "\031\uffc8\032\uffc8\033\uffc8\037\uffc8\040\uffc8\041\uffc8\042" +
    "\uffc8\044\uffc8\045\uffc8\046\uffc8\047\uffc8\050\uffc8\051\uffc8" +
    "\052\uffc8\053\uffc8\056\uffc8\057\uffc8\001\002\000\036\030" +
    "\121\031\130\032\113\033\117\037\114\040\120\041\107" +
    "\042\112\045\uffe6\046\115\047\126\050\127\051\125\052" +
    "\116\001\002\000\046\030\uffa8\031\uffa8\032\uffa8\033\uffa8" +
    "\037\uffa8\040\uffa8\041\uffa8\042\uffa8\044\uffa8\045\uffa8\046" +
    "\uffa8\047\uffa8\050\uffa8\051\uffa8\052\uffa8\053\uffa8\056\uffa8" +
    "\057\uffa8\001\002\000\046\030\uffa7\031\uffa7\032\uffa7\033" +
    "\uffa7\037\uffa7\040\uffa7\041\uffa7\042\uffa7\044\uffa7\045\uffa7" +
    "\046\uffa7\047\uffa7\050\uffa7\051\uffa7\052\uffa7\053\uffa7\056" +
    "\uffa7\057\uffa7\001\002\000\030\006\052\015\075\016\076" +
    "\022\061\023\031\026\032\027\034\043\100\047\104\060" +
    "\077\062\101\001\002\000\030\006\052\015\075\016\076" +
    "\022\061\023\031\026\032\027\034\043\100\047\104\060" +
    "\077\062\101\001\002\000\046\030\uffad\031\uffad\032\uffad" +
    "\033\uffad\037\uffad\040\uffad\041\uffad\042\uffad\044\uffad\045" +
    "\uffad\046\uffad\047\uffad\050\uffad\051\uffad\052\uffad\053\uffad" +
    "\056\uffad\057\uffad\001\002\000\046\030\uffac\031\uffac\032" +
    "\uffac\033\uffac\037\uffac\040\uffac\041\uffac\042\uffac\044\uffac" +
    "\045\uffac\046\uffac\047\uffac\050\uffac\051\uffac\052\uffac\053" +
    "\uffac\056\uffac\057\uffac\001\002\000\046\030\uffae\031\uffae" +
    "\032\uffae\033\uffae\037\uffae\040\uffae\041\uffae\042\uffae\044" +
    "\uffae\045\uffae\046\uffae\047\uffae\050\uffae\051\uffae\052\uffae" +
    "\053\uffae\056\uffae\057\uffae\001\002\000\030\006\052\015" +
    "\075\016\076\022\061\023\031\026\032\027\034\043\100" +
    "\047\104\060\077\062\101\001\002\000\046\030\uffc6\031" +
    "\uffc6\032\uffc6\033\uffc6\037\uffc6\040\uffc6\041\uffc6\042\uffc6" +
    "\044\uffc6\045\uffc6\046\uffc6\047\uffc6\050\uffc6\051\uffc6\052" +
    "\uffc6\053\uffc6\056\uffc6\057\uffc6\001\002\000\046\030\121" +
    "\031\130\032\113\033\117\037\114\040\120\041\107\042" +
    "\112\044\uffc4\045\uffc4\046\uffc4\047\uffc4\050\uffc4\051\uffc4" +
    "\052\uffc4\053\uffc4\056\uffc4\057\uffc4\001\002\000\030\006" +
    "\uffb0\015\uffb0\016\uffb0\022\uffb0\023\uffb0\026\uffb0\027\uffb0" +
    "\043\uffb0\047\uffb0\060\uffb0\062\uffb0\001\002\000\030\006" +
    "\052\015\075\016\076\022\061\023\031\026\032\027\034" +
    "\043\100\047\104\060\077\062\101\001\002\000\030\006" +
    "\uffbd\015\uffbd\016\uffbd\022\uffbd\023\uffbd\026\uffbd\027\uffbd" +
    "\043\uffbd\047\uffbd\060\uffbd\062\uffbd\001\002\000\030\006" +
    "\uffaf\015\uffaf\016\uffaf\022\uffaf\023\uffaf\026\uffaf\027\uffaf" +
    "\043\uffaf\047\uffaf\060\uffaf\062\uffaf\001\002\000\030\006" +
    "\uffb4\015\uffb4\016\uffb4\022\uffb4\023\uffb4\026\uffb4\027\uffb4" +
    "\043\uffb4\047\uffb4\060\uffb4\062\uffb4\001\002\000\030\006" +
    "\uffb2\015\uffb2\016\uffb2\022\uffb2\023\uffb2\026\uffb2\027\uffb2" +
    "\043\uffb2\047\uffb2\060\uffb2\062\uffb2\001\002\000\030\006" +
    "\uffbb\015\uffbb\016\uffbb\022\uffbb\023\uffbb\026\uffbb\027\uffbb" +
    "\043\uffbb\047\uffbb\060\uffbb\062\uffbb\001\002\000\030\006" +
    "\uffb7\015\uffb7\016\uffb7\022\uffb7\023\uffb7\026\uffb7\027\uffb7" +
    "\043\uffb7\047\uffb7\060\uffb7\062\uffb7\001\002\000\030\006" +
    "\uffb3\015\uffb3\016\uffb3\022\uffb3\023\uffb3\026\uffb3\027\uffb3" +
    "\043\uffb3\047\uffb3\060\uffb3\062\uffb3\001\002\000\030\006" +
    "\uffb1\015\uffb1\016\uffb1\022\uffb1\023\uffb1\026\uffb1\027\uffb1" +
    "\043\uffb1\047\uffb1\060\uffb1\062\uffb1\001\002\000\030\006" +
    "\uffb6\015\uffb6\016\uffb6\022\uffb6\023\uffb6\026\uffb6\027\uffb6" +
    "\043\uffb6\047\uffb6\060\uffb6\062\uffb6\001\002\000\030\006" +
    "\uffbe\015\uffbe\016\uffbe\022\uffbe\023\uffbe\026\uffbe\027\uffbe" +
    "\043\uffbe\047\uffbe\060\uffbe\062\uffbe\001\002\000\030\006" +
    "\uffbf\015\uffbf\016\uffbf\022\uffbf\023\uffbf\026\uffbf\027\uffbf" +
    "\043\uffbf\047\uffbf\060\uffbf\062\uffbf\001\002\000\030\006" +
    "\uffbc\015\uffbc\016\uffbc\022\uffbc\023\uffbc\026\uffbc\027\uffbc" +
    "\043\uffbc\047\uffbc\060\uffbc\062\uffbc\001\002\000\030\006" +
    "\uffb8\015\uffb8\016\uffb8\022\uffb8\023\uffb8\026\uffb8\027\uffb8" +
    "\043\uffb8\047\uffb8\060\uffb8\062\uffb8\001\002\000\030\006" +
    "\uffba\015\uffba\016\uffba\022\uffba\023\uffba\026\uffba\027\uffba" +
    "\043\uffba\047\uffba\060\uffba\062\uffba\001\002\000\030\006" +
    "\uffb9\015\uffb9\016\uffb9\022\uffb9\023\uffb9\026\uffb9\027\uffb9" +
    "\043\uffb9\047\uffb9\060\uffb9\062\uffb9\001\002\000\030\006" +
    "\uffb5\015\uffb5\016\uffb5\022\uffb5\023\uffb5\026\uffb5\027\uffb5" +
    "\043\uffb5\047\uffb5\060\uffb5\062\uffb5\001\002\000\046\030" +
    "\121\031\130\032\113\033\117\037\114\040\120\041\107" +
    "\042\112\044\uffc5\045\uffc5\046\115\047\126\050\127\051" +
    "\125\052\116\053\uffc5\056\uffc5\057\uffc5\001\002\000\036" +
    "\030\121\031\130\032\113\033\117\037\114\040\120\041" +
    "\107\042\112\044\133\046\115\047\126\050\127\051\125" +
    "\052\116\001\002\000\046\030\uffc2\031\uffc2\032\uffc2\033" +
    "\uffc2\037\uffc2\040\uffc2\041\uffc2\042\uffc2\044\uffc2\045\uffc2" +
    "\046\uffc2\047\uffc2\050\uffc2\051\uffc2\052\uffc2\053\uffc2\056" +
    "\uffc2\057\uffc2\001\002\000\046\030\121\031\130\032\113" +
    "\033\117\037\114\040\120\041\107\042\112\044\uffc3\045" +
    "\uffc3\046\115\047\126\050\127\051\125\052\116\053\uffc3" +
    "\056\uffc3\057\uffc3\001\002\000\004\045\136\001\002\000" +
    "\024\006\052\007\057\010\063\012\055\013\054\014\060" +
    "\022\061\053\043\054\uffdd\001\002\000\004\054\uffe5\001" +
    "\002\000\034\004\uffed\005\uffed\006\uffed\007\uffed\010\uffed" +
    "\011\uffed\012\uffed\013\uffed\014\uffed\017\uffed\022\uffed\053" +
    "\uffed\054\uffed\001\002\000\004\035\142\001\002\000\030" +
    "\006\052\015\075\016\076\022\061\023\031\026\032\027" +
    "\034\043\100\047\104\060\077\062\101\001\002\000\036" +
    "\030\121\031\130\032\113\033\117\037\114\040\120\041" +
    "\107\042\112\046\115\047\126\050\127\051\125\052\116" +
    "\057\144\001\002\000\030\006\052\015\075\016\076\022" +
    "\061\023\031\026\032\027\034\043\100\047\104\060\077" +
    "\062\101\001\002\000\036\030\121\031\130\032\113\033" +
    "\117\037\114\040\120\041\107\042\112\046\115\047\126" +
    "\050\127\051\125\052\116\053\043\001\002\000\024\006" +
    "\052\007\057\010\063\012\055\013\054\014\060\022\061" +
    "\053\043\054\uffdd\001\002\000\004\054\uffe2\001\002\000" +
    "\004\054\uffde\001\002\000\030\006\052\015\075\016\076" +
    "\022\061\023\031\026\032\027\034\043\100\047\104\060" +
    "\077\062\101\001\002\000\036\030\121\031\130\032\113" +
    "\033\117\037\114\040\120\041\107\042\112\046\115\047" +
    "\126\050\127\051\125\052\116\056\153\001\002\000\054" +
    "\030\uffc9\031\uffc9\032\uffc9\033\uffc9\034\uffc9\035\uffc9\036" +
    "\uffc9\037\uffc9\040\uffc9\041\uffc9\042\uffc9\044\uffc9\045\uffc9" +
    "\046\uffc9\047\uffc9\050\uffc9\051\uffc9\052\uffc9\053\uffc9\056" +
    "\uffc9\057\uffc9\001\002\000\024\006\052\007\057\010\063" +
    "\012\055\013\054\014\060\022\061\053\043\054\uffdd\001" +
    "\002\000\004\054\uffdf\001\002\000\030\006\052\015\075" +
    "\016\076\022\061\023\031\026\032\027\034\043\100\047" +
    "\104\060\077\062\101\001\002\000\036\030\121\031\130" +
    "\032\113\033\117\037\114\040\120\041\107\042\112\044" +
    "\160\046\115\047\126\050\127\051\125\052\116\001\002" +
    "\000\004\053\043\001\002\000\026\006\uffdb\007\uffdb\010" +
    "\uffdb\011\163\012\uffdb\013\uffdb\014\uffdb\022\uffdb\053\uffdb" +
    "\054\uffdb\001\002\000\024\006\052\007\057\010\063\012" +
    "\055\013\054\014\060\022\061\053\043\054\uffdd\001\002" +
    "\000\004\053\043\001\002\000\024\006\uffdc\007\uffdc\010" +
    "\uffdc\012\uffdc\013\uffdc\014\uffdc\022\uffdc\053\uffdc\054\uffdc" +
    "\001\002\000\004\054\uffe3\001\002\000\032\006\052\015" +
    "\075\016\076\022\061\023\031\026\032\027\034\043\100" +
    "\044\uffd2\047\104\060\077\062\101\001\002\000\040\030" +
    "\121\031\130\032\113\033\117\037\114\040\120\041\107" +
    "\042\112\044\uffd0\046\115\047\126\050\127\051\125\052" +
    "\116\057\172\001\002\000\004\044\171\001\002\000\046" +
    "\030\uffd5\031\uffd5\032\uffd5\033\uffd5\037\uffd5\040\uffd5\041" +
    "\uffd5\042\uffd5\044\uffd5\045\uffd5\046\uffd5\047\uffd5\050\uffd5" +
    "\051\uffd5\052\uffd5\053\uffd5\056\uffd5\057\uffd5\001\002\000" +
    "\030\006\052\015\075\016\076\022\061\023\031\026\032" +
    "\027\034\043\100\047\104\060\077\062\101\001\002\000" +
    "\004\044\uffd3\001\002\000\040\030\121\031\130\032\113" +
    "\033\117\037\114\040\120\041\107\042\112\044\uffd0\046" +
    "\115\047\126\050\127\051\125\052\116\057\172\001\002" +
    "\000\004\044\uffd1\001\002\000\036\030\121\031\130\032" +
    "\113\033\117\037\114\040\120\041\107\042\112\045\uffda" +
    "\046\115\047\126\050\127\051\125\052\116\001\002\000" +
    "\004\045\200\001\002\000\024\006\052\007\057\010\063" +
    "\012\055\013\054\014\060\022\061\053\043\054\uffdd\001" +
    "\002\000\004\054\uffe1\001\002\000\024\006\052\007\057" +
    "\010\063\012\055\013\054\014\060\022\061\053\043\054" +
    "\uffdd\001\002\000\004\054\uffe0\001\002\000\024\006\052" +
    "\007\057\010\063\012\055\013\054\014\060\022\061\053" +
    "\043\054\uffdd\001\002\000\004\054\uffe4\001\002\000\004" +
    "\063\207\001\002\000\006\044\uffce\057\210\001\002\000" +
    "\032\006\052\015\075\016\076\022\061\023\031\026\032" +
    "\027\034\043\100\047\104\060\077\062\101\063\214\001" +
    "\002\000\004\044\212\001\002\000\046\030\uffd4\031\uffd4" +
    "\032\uffd4\033\uffd4\037\uffd4\040\uffd4\041\uffd4\042\uffd4\044" +
    "\uffd4\045\uffd4\046\uffd4\047\uffd4\050\uffd4\051\uffd4\052\uffd4" +
    "\053\uffd4\056\uffd4\057\uffd4\001\002\000\040\030\121\031" +
    "\130\032\113\033\117\037\114\040\120\041\107\042\112" +
    "\044\uffc1\046\115\047\126\050\127\051\125\052\116\057" +
    "\uffc1\001\002\000\006\044\uffc0\057\uffc0\001\002\000\006" +
    "\044\uffcc\057\216\001\002\000\032\006\052\015\075\016" +
    "\076\022\061\023\031\026\032\027\034\043\100\047\104" +
    "\060\077\062\101\063\214\001\002\000\004\044\uffcf\001" +
    "\002\000\006\044\uffcc\057\216\001\002\000\004\044\uffcd" +
    "\001\002\000\006\045\uffe9\057\224\001\002\000\004\045" +
    "\227\001\002\000\004\022\225\001\002\000\006\045\uffe9" +
    "\057\224\001\002\000\004\045\uffea\001\002\000\030\004" +
    "\016\005\017\006\uffeb\007\uffeb\010\uffeb\012\uffeb\013\uffeb" +
    "\014\uffeb\022\uffeb\053\uffeb\054\uffeb\001\002\000\024\006" +
    "\uffec\007\uffec\010\uffec\012\uffec\013\uffec\014\uffec\022\uffec" +
    "\053\uffec\054\uffec\001\002\000\006\044\ufff3\057\ufff3\001" +
    "\002\000\006\044\uffee\057\233\001\002\000\006\004\016" +
    "\005\017\001\002\000\004\044\ufff2\001\002\000\004\022" +
    "\236\001\002\000\006\044\ufff0\057\ufff0\001\002\000\006" +
    "\044\uffee\057\233\001\002\000\004\044\uffef\001\002\000" +
    "\004\002\uffff\001\002\000\004\043\243\001\002\000\010" +
    "\004\016\005\017\044\ufff1\001\002\000\004\044\245\001" +
    "\002\000\004\053\ufff6\001\002\000\004\053\043\001\002" +
    "\000\012\004\016\005\017\017\013\054\ufff4\001\002\000" +
    "\004\054\ufff5\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\006\002\005\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\011\001\001\000\006\005" +
    "\013\010\014\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\031\020\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\037\022\001\001\000\004" +
    "\031\025\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\037\026\001\001\000\002\001\001" +
    "\000\004\026\032\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\010\036\032\037\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\044\041\001\001\000\004\006\043" +
    "\001\001\000\006\007\050\010\047\001\001\000\006\005" +
    "\044\010\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\006\061\011" +
    "\063\013\052\014\055\015\064\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\013\071\014" +
    "\055\015\072\016\175\025\104\026\102\027\101\036\176" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\006\061\011\147\013\052" +
    "\014\055\015\064\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\067\001\001\000\002\001\001\000\002" +
    "\001\001\000\020\013\071\014\055\015\072\016\073\025" +
    "\104\026\102\027\101\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\020\107\021\122\022" +
    "\121\023\110\024\123\050\134\001\001\000\002\001\001" +
    "\000\002\001\001\000\020\013\071\014\055\015\072\016" +
    "\133\025\104\026\102\027\101\001\001\000\020\013\071" +
    "\014\055\015\072\016\131\025\104\026\102\027\101\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\013\071\014\055\015\072\016\105\025\104\026" +
    "\102\027\101\001\001\000\002\001\001\000\014\020\107" +
    "\021\122\022\121\023\110\024\123\001\001\000\002\001" +
    "\001\000\020\013\071\014\055\015\072\016\130\025\104" +
    "\026\102\027\101\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\020\107\021\122\022\121" +
    "\023\110\024\123\001\001\000\014\020\107\021\122\022" +
    "\121\023\110\024\123\001\001\000\002\001\001\000\014" +
    "\020\107\021\122\022\121\023\110\024\123\001\001\000" +
    "\002\001\001\000\014\006\061\011\136\013\052\014\055" +
    "\015\064\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\013\071\014\055\015\072\016\142" +
    "\025\104\026\102\027\101\001\001\000\014\020\107\021" +
    "\122\022\121\023\110\024\123\001\001\000\020\013\071" +
    "\014\055\015\072\016\144\025\104\026\102\027\101\001" +
    "\001\000\016\006\145\020\107\021\122\022\121\023\110" +
    "\024\123\001\001\000\014\006\061\011\146\013\052\014" +
    "\055\015\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\013\071\014\055\015\072\016\151\025\104\026" +
    "\102\027\101\001\001\000\014\020\107\021\122\022\121" +
    "\023\110\024\123\001\001\000\002\001\001\000\014\006" +
    "\061\011\154\013\052\014\055\015\064\001\001\000\002" +
    "\001\001\000\020\013\071\014\055\015\072\016\156\025" +
    "\104\026\102\027\101\001\001\000\014\020\107\021\122" +
    "\022\121\023\110\024\123\001\001\000\004\006\160\001" +
    "\001\000\004\035\161\001\001\000\014\006\061\011\164" +
    "\013\052\014\055\015\064\001\001\000\004\006\163\001" +
    "\001\000\002\001\001\000\002\001\001\000\022\013\071" +
    "\014\055\015\072\016\166\025\104\026\102\027\101\040" +
    "\167\001\001\000\016\020\107\021\122\022\121\023\110" +
    "\024\123\041\172\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\013\071\014\055\015\072\016\173\025\104" +
    "\026\102\027\101\001\001\000\002\001\001\000\016\020" +
    "\107\021\122\022\121\023\110\024\123\041\174\001\001" +
    "\000\002\001\001\000\014\020\107\021\122\022\121\023" +
    "\110\024\123\001\001\000\002\001\001\000\014\006\061" +
    "\011\200\013\052\014\055\015\064\001\001\000\002\001" +
    "\001\000\014\006\061\011\202\013\052\014\055\015\064" +
    "\001\001\000\002\001\001\000\014\006\061\011\204\013" +
    "\052\014\055\015\064\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\042\210\001\001\000\022\013\071\014" +
    "\055\015\072\016\212\017\214\025\104\026\102\027\101" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\020" +
    "\107\021\122\022\121\023\110\024\123\001\001\000\002" +
    "\001\001\000\004\043\216\001\001\000\022\013\071\014" +
    "\055\015\072\016\212\017\217\025\104\026\102\027\101" +
    "\001\001\000\002\001\001\000\004\043\220\001\001\000" +
    "\002\001\001\000\004\034\222\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\034\225\001\001\000\002\001" +
    "\001\000\006\007\227\010\047\001\001\000\002\001\001" +
    "\000\004\046\231\001\001\000\004\033\233\001\001\000" +
    "\004\010\234\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\047\236\001\001\000\004\033\237\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\010\036\032\243\001\001\000\002\001\001\000\004\045" +
    "\245\001\001\000\004\006\246\001\001\000\006\005\247" +
    "\010\045\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$IRT$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$IRT$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$IRT$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    public String resultado="";
    public Nodo padre;
    public int contador = 1;
    public void syntax_error(Symbol s){
        //this.s = s;
        System.out.println("Error Sintactico en la Linea " + (s.right+1) +" Columna: " +(s.left)+ ". Identificador " +s.value + " no reconocido." + "el type: " + s.sym);
    }
    public void unrecovered_syntax_error(Symbol s){
        System.out.println(s);
    }

    public Symbol getS(){
        return this.s;
    }
    public Nodo_irt mdc = new Nodo_irt("parametros");
    public ArrayList<Nodo_irt> Lista_IRT = new ArrayList<>();

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$IRT$actions {
  private final IRT parser;

  /** Constructor */
  CUP$IRT$actions(IRT parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$IRT$do_action(
    int                        CUP$IRT$act_num,
    java_cup.runtime.lr_parser CUP$IRT$parser,
    java.util.Stack            CUP$IRT$stack,
    int                        CUP$IRT$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$IRT$result;

      /* select the action based on the action number */
      switch (CUP$IRT$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // bool_literal ::= False 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("bool_literal",21, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // bool_literal ::= True 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("bool_literal",21, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // int_literal ::= Digit 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("int_literal",20, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // int_literal ::= Hex_literal 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("int_literal",20, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // int_literal ::= Decimal_literal 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("int_literal",20, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // literal ::= bool_literal 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("literal",19, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // literal ::= CHAR_LITERAL 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("literal",19, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // literal ::= int_literal 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("literal",19, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // cond_op ::= OR 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("cond_op",18, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // cond_op ::= AND 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("cond_op",18, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // eq_op ::= NOT_EQUAL 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("eq_op",17, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // eq_op ::= EQUAL 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("eq_op",17, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // rel_op ::= GREATER_EQUAL 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("rel_op",16, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // rel_op ::= LESS_EQUAL 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("rel_op",16, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // rel_op ::= LESS 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("rel_op",16, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // rel_op ::= GREATER 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("rel_op",16, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // arith_op ::= Mod 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("arith_op",15, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // arith_op ::= Division 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("arith_op",15, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // arith_op ::= Multiplicacion 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("arith_op",15, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // arith_op ::= Menos 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("arith_op",15, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // arith_op ::= Mas 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("arith_op",15, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // bin_op ::= cond_op 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("bin_op",14, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // bin_op ::= eq_op 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("bin_op",14, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // bin_op ::= rel_op 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("bin_op",14, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // bin_op ::= arith_op 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("bin_op",14, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // callout_arg ::= STRING_LITERAL 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("callout_arg",13, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // callout_arg ::= expr 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("callout_arg",13, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= LEFT_PAR expr RIGHT_PAR 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("expr",12, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= Exclamacion expr 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("expr",12, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= Menos expr 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("expr",12, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= expr bin_op expr 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("expr",12, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= literal 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("expr",12, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= method_call 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("expr",12, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= location 
            {
              Object RESULT =null;
		int loleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).left;
		int loright = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).right;
		Object lo = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.peek()).value;
		 
            String loc_ = ("" + lo);
            RESULT = loc_;
        
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("expr",12, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // location ::= Id Corche_A expr Corche_C 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-3)).value;
		
            String id_ = ("" + id);
            RESULT = id_;
            
        
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("location",11, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // location ::= Id 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.peek()).value;
		 
            String id_ = ("" + id);
            RESULT = id_;
        
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("location",11, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // method_name ::= Id 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_name",10, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // method_call_coma_callout ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call_coma_callout",33, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // method_call_coma_callout ::= Coma callout_arg method_call_coma_callout 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call_coma_callout",33, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // method_call_corche_dos ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call_corche_dos",32, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // method_call_corche_dos ::= Coma callout_arg method_call_coma_callout 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call_corche_dos",32, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // method_call_corche_expr ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call_corche_expr",31, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // method_call_corche_expr ::= Coma expr method_call_corche_expr 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call_corche_expr",31, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // method_call_corche ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call_corche",30, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // method_call_corche ::= expr method_call_corche_expr 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call_corche",30, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // method_call ::= Callout LEFT_PAR STRING_LITERAL method_call_corche_dos RIGHT_PAR 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call",9, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-4)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // method_call ::= method_name LEFT_PAR method_call_corche RIGHT_PAR 
            {
              Object RESULT =null;
		
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_call",9, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // assign_op ::= MINUS_EQUAL 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("assign_op",8, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // assign_op ::= PLUS_EQUAL 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("assign_op",8, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // assign_op ::= ASSIGN 
            {
              Object RESULT =null;
		int asleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).left;
		int asright = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).right;
		Object as = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.peek()).value;
		
            String as_ = ("" + as);
            RESULT = as_;
             
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("assign_op",8, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // statement_expr ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement_expr",28, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // statement_expr ::= expr 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement_expr",28, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // statement_else_block ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement_else_block",27, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // statement_else_block ::= Else block 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement_else_block",27, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // statement ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // statement ::= block statement 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // statement ::= Continue Punto_coma statement 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // statement ::= Break Punto_coma statement 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // statement ::= Return statement_expr Punto_coma statement 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // statement ::= For Id ASSIGN expr Coma expr block statement 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-7)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // statement ::= If LEFT_PAR expr RIGHT_PAR block statement_else_block statement 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-6)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // statement ::= method_call Punto_coma statement 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // statement ::= location assign_op expr NT$4 Punto_coma statement 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-2)).value;
		int locleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-5)).left;
		int locright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-5)).right;
		Object loc = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-5)).value;
		int asileft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-4)).left;
		int asiright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-4)).right;
		Object asi = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-4)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)).right;
		Object ex = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-3)).value;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-5)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // NT$4 ::= 
            {
              Object RESULT =null;
		int locleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)).left;
		int locright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)).right;
		Object loc = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-2)).value;
		int asileft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)).left;
		int asiright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)).right;
		Object asi = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-1)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).right;
		Object ex = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.peek()).value;
 
                Nodo_irt asignacion = new Nodo_irt("Asignacion");
                 String a = (String) asi;
                 String exx = (String) ex;
                 String locc = (String) loc;
                asignacion.Crear_Asignacion(a, exx, locc);
                parser.Lista_IRT.add(asignacion);
                
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("NT$4",38, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // type ::= Boolean 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // type ::= Int 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("type",6, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // var_decl_coma_id ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("var_decl_coma_id",26, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // var_decl_coma_id ::= Coma Id var_decl_coma_id 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("var_decl_coma_id",26, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // var_decl ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("var_decl",5, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // var_decl ::= type Id var_decl_coma_id Punto_coma var_decl 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("var_decl",5, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-4)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // block ::= Llave_A var_decl statement Llave_C 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("block",4, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // method_decl_corche_coma_type ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_decl_corche_coma_type",25, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // method_decl_corche_coma_type ::= Coma type Id NT$3 method_decl_corche_coma_type 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-2)).value;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_decl_corche_coma_type",25, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-4)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NT$3 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.peek()).value;
 
            parser.mdc.parametros_nodo.addParame("" + id);
        
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("NT$3",37, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // method_decl_corche ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_decl_corche",24, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // method_decl_corche ::= type Id NT$2 method_decl_corche_coma_type 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-2)).value;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_decl_corche",24, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // NT$2 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.peek()).value;
 
            parser.mdc.Crear_parametros();
            parser.mdc.parametros_nodo.addParame("" + id);

         
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("NT$2",36, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // method_decl ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_decl",3, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // method_decl ::= Void Id LEFT_PAR method_decl_corche RIGHT_PAR NT$1 block method_decl 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-6)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-6)).value;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_decl",3, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-7)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$1 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-3)).value;
 
                        Nodo_irt metodo = new Nodo_irt("Metodo");
                        if (parser.mdc.parametros_nodo != null)
                            {
                                metodo.Crear_method(("" + id), parser.mdc.parametros_nodo.getParame());
                                parser.Lista_IRT.add(metodo);
                                parser.mdc.parametros_nodo.Clear_parame();
                        }
                        else {
                                metodo.Crear_method(("" + id), "parametros: ()");
                                parser.Lista_IRT.add(metodo);
                                }
                
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("NT$1",35, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // method_decl ::= type Id LEFT_PAR method_decl_corche RIGHT_PAR NT$0 block method_decl 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-6)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-6)).value;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("method_decl",3, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-7)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$0 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-3)).value;
 
                        Nodo_irt metodo = new Nodo_irt("Metodo");
                        if (parser.mdc.parametros_nodo != null)
                            {
                                metodo.Crear_method(("" + id), parser.mdc.parametros_nodo.getParame());
                                parser.Lista_IRT.add(metodo);
                                parser.mdc.parametros_nodo.Clear_parame();
                        }
                        else {
                                metodo.Crear_method(("" + id), "parametros: ()");
                                parser.Lista_IRT.add(metodo);
                                }
                        
                        
                
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("NT$0",34, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // field_decl_coma_field ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("field_decl_coma_field",29, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // field_decl_coma_field ::= Coma field_name field_decl_coma_field 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("field_decl_coma_field",29, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-2)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // field_decl ::= 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("field_decl",2, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // field_decl ::= field_decl type field_name field_decl_coma_field Punto_coma 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("field_decl",2, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-4)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // field_name ::= Id Corche_A int_literal Corche_C 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("field_name",23, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-3)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // field_name ::= Id 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("field_name",23, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= Class Program Llave_A field_decl method_decl Llave_C 
            {
              Object RESULT =null;

              CUP$IRT$result = parser.getSymbolFactory().newSymbol("program",1, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-5)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= program 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.peek()).value;
		
            System.out.println("Correcto");
        
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          return CUP$IRT$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$IRT$stack.elementAt(CUP$IRT$top-1)).value;
		RESULT = start_val;
              CUP$IRT$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$IRT$stack.elementAt(CUP$IRT$top-1)), ((java_cup.runtime.Symbol)CUP$IRT$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$IRT$parser.done_parsing();
          return CUP$IRT$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

